### ISSUE TITLE
duplicate time issues from original dataset

### ISSUE THREAD

**Issue by yunfangsun** [oceanmodeling/StormEvents#81]
I have used stormevents to download the Hurricane IAN 2022's best track file. Because there are duplicate time slots in the original data sever, the outputs from stormevents keep the duplicate data.

When I try to use the hurricane track file to run PaHM case, it generate errors "InitLogging not called :: ProcessAsymmetricVortexData: 4 isotachs were nonzero." the details could be found at [PaHM issue 26](https://github.com/noaa-ocs-modeling/PaHM/issues/26).

Is there a way to normalize the stormevents or PaHM scripts to avoid such kind of errors?
@SorooshMani-NOAA @pvelissariou1

**Comment by SorooshMani-NOAA** [comment]
Thanks for creating this issue. As we discussed during the meeting and on https://github.com/noaa-ocs-modeling/PaHM/issues/26, the source of the issue is the original data from ATCF file. We need to add explicit *normalization* methods/functions in `stormevents`.

Right now AFAIK there's an implicit normalization for `OFCL` advisory to fix eye and background pressure.

I was thinking about adding a method like `normalize_for_parametric_models()` method to the `VortexTrack` class so that one can explicitly ask for the normalization such as removing duplicates for a given forecast time.

I also think ideally the fix for pressures (which happens implicitly right now) need to be explicit rather than implicit. What do you think @WPringle

**Comment by WPringle** [comment]
@SorooshMani-NOAA Doing some cleaning up explicitly could make sense I agree.

**Comment by SorooshMani-NOAA** [comment]
Close as duplicate!
